h_m = float(input("height(m): "))
w_k = float(input("weight(kg): "))
h_i = float(input("height(inches): "))
w_p = float(input("weight(pounds): "))
print(str((w_p / (h_i)**2)*703))
print(str(w_k / (h_m)**2))
